modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Compact%20Help%20Command"
logoFile="icon.png"

[[mods]]
modId="compacthelpcommand"
version="2.4"
displayName="Compact Help Command"
displayURL="https://curseforge.com/minecraft/mc-mods/compact-help-command"
authors="Rick South"
description='''Modifies the standard /help command to be colourful and have multiple pages.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.compacthelpcommand]]
    modId="collective"
    mandatory=true
    versionRange="[7.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.compacthelpcommand]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "compacthelpcommand_neoforge.mixins.json"