modLoader="javafml"
loaderVersion="*"
license="All Rights Reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Compact%20Help%20Command"
logoFile="icon.png"

[[mods]]
modId="compacthelpcommand"
version="3.0"
displayName="Compact Help Command"
displayURL="https://serilum.com/mod/compact-help-command"
authors="Serilum"
description='''Modifies the standard /help command to be colourful and have multiple pages.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Andrean Olgo, AnyankaT, aternosorg, Cherriesaurus, Linda Jansen, MWS, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate Appreciate it! <3   
'''

[[dependencies.compacthelpcommand]]
    modId="collective"
    type="required"
    versionRange="[8.40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.compacthelpcommand]]
    modId="minecraft"
    type="required"
    versionRange="[26.2]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "compacthelpcommand.mixins.json"